#!/bin/bash

# Script to install all currently installed VS Code extensions
code --install-extension alexcvzz.vscode-sqlite --force
code --install-extension antonreshetov.masscode-assistant --force
code --install-extension bradlc.vscode-tailwindcss --force
code --install-extension codesandbox-io.codesandbox-projects --force
code --install-extension csstools.postcss --force
code --install-extension donjayamanne.githistory --force
code --install-extension druideinformatique.antidote --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension github.copilot --force
code --install-extension github.copilot-chat --force
code --install-extension github.vscode-github-actions --force
code --install-extension jock.svg --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension ms-python.black-formatter --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.isort --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension ms-vscode-remote.remote-ssh-edit --force
code --install-extension ms-vscode.remote-explorer --force
code --install-extension naumovs.color-highlight --force
code --install-extension pwabuilder.pwa-studio --force
code --install-extension redhat.vscode-yaml --force
code --install-extension ritwickdey.liveserver --force
code --install-extension stivo.tailwind-fold --force
code --install-extension tomoki1207.pdf --force
code --install-extension usernamehw.errorlens --force
code --install-extension visualstudioexptteam.intellicode-api-usage-examples --force
code --install-extension visualstudioexptteam.vscodeintellicode --force
code --install-extension vscode-icons-team.vscode-icons --force
code --install-extension yy0931.vscode-sqlite3-editor --force
